#!/bin/bash
#export PATH="$PATH:/media/Nvme_Data/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd"

PS3='Please enter your choice: '
options=( "Download Mods" "Edit Mods List" "sysLinks Mods folder" "unlinks" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "sysLinks Mods folder")
            ln -s /media/Nvme_Data/Games/workshop/steamapps/workshop/content/294100/* /media/Nvme_Data/Games/Rimworld-jc141/files/groot/Mods/
            ;;
        "Download Mods")
            #/media/Nvme_Data/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/steamcmd.sh +runscript rimmod
            xargs -P 10 -n 1 rimdown < rimmods
            ln -s /media/Nvme_Data/Games/workshop/steamapps/workshop/content/294100/* /media/Nvme_Data/Games/Rimworld-jc141/files/groot/Mods/
            break
            ;;

        "Edit Mods List")
            mousepad /media/Nvme_Data/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/rimmod
        ;;
        "Quit")
            break
            ;;
        "unlinks")
            unlink /media/Nvme_Data/Games/Rimworld-jc141/files/groot/Mods/*
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

rimdown() {
	/media/Nvme_Data/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/steamcmd.sh +force_install_dir /media/Nvme_Data/Games/workshop/ +login anonymous +workshop_download_item 294100 $1 +exit
	}

