#!/bin/bash
#export PATH="$PATH:/home/vugia/GAMES/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd"
rimdown() {
	/home/vugia/GAMES/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/steamcmd.sh \
		+force_install_dir /home/vugia/GAMES/Games/workshop/ +login anonymous +workshop_download_item 294100 "$1" +quit
	}

rimdown-script() {
	/home/vugia/GAMES/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/steamcmd.sh +runscript "$1" +quit
	}

export -f rimdown
PS3='Please enter your choice: '
options=( "Download All Mods" "Edit Mods List" "Download New Mods" "unlinks" "rm acf" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        # "sysLinks Mods folder")
        #   cd /home/vugia/GAMES/Games/RimWorld/ && rm -rf Mods
        #   ln -s /home/vugia/GAMES/Games/workshop/steamapps/workshop/content/294100/ Mods
        #     ;;
        "Download All Mods")
            gawk -i inplace '!a[$0]++' /home/vugia/GAMES/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/rimmod
            rimdown-script rimmod
            #cd /home/vugia/GAMES/Games/Rimworld-jc141/
            #parallel -j 5 git clone {} < rimmods
            #ln -sf /home/vugia/GAMES/Games/workshop/steamapps/workshop/content/294100/* /home/vugia/GAMES/Games/Rimworld-jc141/files/groot/Mods/
            #ln -sf /home/vugia/GAMES/Games/workshop/steamapps/workshop/content/294100/* /home/vugia/GAMES/Games/RimWorld/Mods/
            /bin/rm -rf /home/vugia/Steam/logs/*
            #/bin/rm -rf /home/vugia/GAMES/Games/workshop/steamapps/workshop/appworkshop_294100.acf
            break
        ;;
        "Edit Mods List")
            mousepad /home/vugia/GAMES/Games/Rimworld-jc141/SteamModDownloader/scripts/steamcmd/rimmod /home/vugia/clip.txt
        ;;
        "Download New Mods")
            rimdown-script rimmodnew
            #ln -sf /home/vugia/GAMES/Games/workshop/steamapps/workshop/content/294100/* /home/vugia/GAMES/Games/Rimworld-jc141/files/groot/Mods/
            #ln -sf /home/vugia/GAMES/Games/workshop/steamapps/workshop/content/294100/* /home/vugia/GAMES/Games/RimWorld/Mods/
            /bin/rm -rf /home/vugia/Steam/logs/*
            break
        ;;
        "Quit")
            break
            ;;
        "unlinks")
            unlink /home/vugia/GAMES/Games/Rimworld-jc141/files/groot/Mods/
            break
        ;;
        "rm acf")
            /bin/rm -rf /home/vugia/GAMES/Games/workshop/steamapps/workshop/appworkshop_294100.acf
            break
        ;;
        *) echo "invalid option $REPLY";;
    esac
done