general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"
opacity = "0.9"
size = "15"
normal = '{ family = "Space Mono for Powerline", style = "Regular" }'
