general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"
[window]
dimensions = { columns = 144, lines = 43 }
position = { x = 0, y = 11}
decorations = "None"
opacity = 0.95
[font]
size = 15
normal = { family = "Space Mono for Powerline", style = "Regular" }
#dimensions = '{ columns =70 , lines =70 }'
#padding = '{ x = 170, y = 170 }'

[terminal]
shell = { program = "/bin/tmux", args = ["new-session"]}

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
# { key = "T", mods = "Control", action = "CreateNewWindow" },
{ key = "-", mods = "Control", action = "DecreaseFontSize"},
{ key = "=", mods = "Control", action = "IncreaseFontSize" },
]
